import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "MesloLGLDZ Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGLDZ Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGLDZ Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGLDZ Nerd Font Mono"
style = "Regular"
